### DISCUSSION TITLE
File-Based catalog auto-release

### DISCUSSION THREAD

**Discussion by Allda** [redhat-openshift-ecosystem/community-operators-prod#6164] [Announcements]
Hello, operator maintainers!

**TLDR**: A single pull request is now needed to release a new operator bundle to the File-Based Catalog.

Today, I would like to announce a simplification of the File-Based Catalog (FBC) release process by introducing the FBC auto-release feature 🎉.

Last year, we introduced the FBC catalog distribution method that required raising 2 pull-requests: one with a new operator bundle and the other with catalog changes. This process was challenging, especially for automated workflows. Now, with the auto-release feature, this **process is simplified and requires just a single pull request**.

The new process is described in our [documentation](https://redhat-openshift-ecosystem.github.io/operator-pipelines/users/fbc_autorelease/).

To enable the feature, you just need to add one additional file to your bundle with the following content:

```yaml
operators/<operator>/<version>release-config.yaml

---
catalog_templates:
  - template_name: my_basic_template.yaml
    channels: [alpha, beta]
    replaces: my_operator.0.0.1
  - template_name: my_semver_template.yaml
    channels: [Fast, Stable]
```

This file, together with a FBC  [template mapping in ci.yaml](https://redhat-openshift-ecosystem.github.io/operator-pipelines/users/fbc_workflow/#fbc-template-mapping) will automatically build a bundle and release it to the right OCP catalog verion based on your preferences.
