### ISSUE TITLE
CI: Deployment tests against OCP passing when the Operator deployment is not successfully  deployed.

### ISSUE THREAD

**Issue by camilamacedo86** [redhat-openshift-ecosystem/community-operators-prod#1288]
See the PR: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1287. The CI test passed against OCP < 4.11 when it should fail since the deployment will not succeed.

The deployment of the Pod fails with : 

```
 lastTransitionTime: '2022-06-12T21:36:53Z'
      lastUpdateTime: '2022-06-12T21:36:53Z'
      message: >-
        install failed: deployment memcached-operator-controller-manager not
        ready before timeout: deployment "memcached-operator-controller-manager"
        exceeded its progress deadline
      phase: Failed
      reason: InstallCheckFailed
```

We should be checking if the installation and deployment of the Operator occurred successfully as should be: 

```yaml
      message: install strategy completed with no errors
      phase: Succeeded
      reason: InstallSucceeded
````
