### ISSUE TITLE
The community index image missed some etcd operator versions

### ISSUE THREAD

**Issue by jianzhangbjz** [redhat-openshift-ecosystem/community-operators-prod#306]
As you can see from the below, only the v0.6.1/v0.9.4 versions are in this `registry.redhat.io/redhat/community-operator-index:v4.9` index image. But, in fact, there is the v0.9.2 version in the https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/etcd source code. I'd suggest that we add them into this community index image so that align with the source code, thanks!
```yaml
[cloud-user@preserve-olm-env jian]$ oc port-forward community-operators-89rpn 50051
Forwarding from 127.0.0.1:50051 -> 50051
Forwarding from [::1]:50051 -> 50051
Handling connection for 50051
...
[cloud-user@preserve-olm-env jian]$ grpcurl -plaintext -d '{"name":"etcd"}' localhost:50051 api.Registry/GetPackage
{
  "name": "etcd",
  "channels": [
    {
      "name": "alpha",
      "csvName": "etcdoperator.v0.6.1"
    },
    {
      "name": "clusterwide-alpha",
      "csvName": "etcdoperator.v0.9.4-clusterwide"
    },
    {
      "name": "singlenamespace-alpha",
      "csvName": "etcdoperator.v0.9.4"
    }
  ],
  "defaultChannelName": "singlenamespace-alpha"
}
```

**Comment by camilamacedo86** [comment]
Hi @jianzhangbjz, 

Could you please check it now? The 4.9 indexes was generated successfully.
Please, let us know if you find any issue.

**Comment by camilamacedo86** [comment]
Could we close this one?

**Comment by camilamacedo86** [comment]
Hi @jianzhangbjz, 

By looking at the audit reports I can see that the following bundles are published on 4.9.
Seems like that the command used in https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/306#issuecomment-952560347 is only returning the head of channels.

**Comment by camilamacedo86** [comment]
Hi @jianzhangbjz, 

Could you please try to use the endpoint `ListBundles`? It shows that the `GetPackage` returns PackageManifest object which only presents the head of the channel. It has been always the case and with `ListBundles` you can get all the bundles in an image. 

Please, let me know if it will solve the problem and if we can close this one.

**Comment by jianzhangbjz** [comment]
Hi @camilamacedo86 Yes, it works well and I can find all etcdoperator versions. Many thanks for your help! Sorry for my mistake, close it.
```yaml
mac:~ jianzhang$ grpcurl -plaintext localhost:50051  api.Registry/ListBundles |grep etcdoperator -A 3
  "csvName": "etcdoperator.v0.6.1",
  "packageName": "etcd",
  "channelName": "alpha",
  "bundlePath": "quay.io/openshift-community-operators/etcd@sha256:7f689b4d96172a6ee2a7b86d9ca554239e4d51b75e6235fa5a0f359a108877fb",
--
  "csvName": "etcdoperator.v0.9.0",
  "packageName": "etcd",
  "channelName": "clusterwide-alpha",
  "bundlePath": "quay.io/openshift-community-operators/etcd@sha256:a6f69bf73af305f0beabf23b10dbc76efce897468fe21308c0527bc095fd4c66",
--
  "csvName": "etcdoperator.v0.9.0",
  "packageName": "etcd",
  "channelName": "singlenamespace-alpha",
  "bundlePath": "quay.io/openshift-community-operators/etcd@sha256:a6f69bf73af305f0beabf23b10dbc76efce897468fe21308c0527bc095fd4c66",
--
  "csvName": "etcdoperator.v0.9.2",
  "packageName": "etcd",
  "channelName": "singlenamespace-alpha",
  "bundlePath": "quay.io/openshift-community-operators/etcd@sha256:d976e5a01b20e39c4227bca469cf6c6744e61d1140ac1d4db994154f4b451a81",
--
  "replaces": "etcdoperator.v0.9.0"
}
{
  "csvName": "etcdoperator.v0.9.2-clusterwide",
  "packageName": "etcd",
  "channelName": "clusterwide-alpha",
  "bundlePath": "quay.io/openshift-community-operators/etcd@sha256:80c4690a6c9d2cf533ee5b505e675a572f5b0f96de48e82893a3fe6cce5219be",
--
  "replaces": "etcdoperator.v0.9.0"
}
{
  "csvName": "etcdoperator.v0.9.4",
  "packageName": "etcd",
  "channelName": "singlenamespace-alpha",
  "bundlePath": "quay.io/openshift-community-operators/etcd@sha256:94346b5ee6149d1411b2f37f815526db3b86e62a03879337f6194428d52c336e",
--
  "replaces": "etcdoperator.v0.9.2"
}
{
  "csvName": "etcdoperator.v0.9.4-clusterwide",
  "packageName": "etcd",
  "channelName": "clusterwide-alpha",
  "bundlePath": "quay.io/openshift-community-operators/etcd@sha256:3bc855e2b0eb9950854f6e36f4d697eb424a9dbe6e331ff3cf7924a0d8e3ecab",
--
  "replaces": "etcdoperator.v0.9.2-clusterwide"
}
{
  "csvName": "flux.v0.13.4",
```
