### ISSUE TITLE
Flakey Test: `operator/test` DeployableByOLM: insufficient information in logs to know what caused the failure

### ISSUE THREAD

**Issue by wallrj** [redhat-openshift-ecosystem/community-operators-prod#3998]
@Allda Can you help me understand how to fix failed `operator/test` check?

```yaml
        "errors": [
            {
                "name": "DeployableByOLM",
                "elapsed_time": 251130,
                "description": "Checking if the operator could be deployed by OLM",
                "help": "It is required that your operator could be deployed by OLM"
            }
        ],
```
-- https://gist.github.com/rh-operator-bundle-bot/aca8f1384f5ddf0b97443910c0efe69f#file-preflight-stdout-L29

> time="2024-02-07T15:16:40Z" level=info msg="check completed" check=DeployableByOLM err="error: watch: could not retrieve the object cert-manager-target/cert-manager.v1.13.3: failed to fetch the csv cert-manager.v1.13.3 from namespace cert-manager-target: could not retrieve csv: cert-manager-target/cert-manager.v1.13.3: client rate limiter Wait returned an error: context deadline exceeded" result=ERROR

-- https://gist.github.com/rh-operator-bundle-bot/aca8f1384f5ddf0b97443910c0efe69f#file-preflight-stderr-L998

https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/068aa754f1b8aa02d599ed3ddefa71575d020898/internal/policy/operator/deployable_by_olm.go#L113-L179

_Originally posted by @wallrj in https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/3992#issuecomment-1932344791_

I see other examples of this bug in the PRs of other operators:
 * https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3946#issuecomment-1931942341

/kind bug
