### ISSUE TITLE
oc-mirror does not tag grafana operator properly [disconnected]

### ISSUE THREAD

**Issue by jnm27** [redhat-openshift-ecosystem/community-operators-prod#5212]
Excerpt from imageset-config.yml:

```
    - catalog: registry.redhat.io/redhat/community-operator-index:v4.16
      targetCatalog: my/community-operator-index
      packages:
        - name: grafana-operator
          channels:
            - name: v5
              minVersion: 5.13.0
              maxVersion: 5.13.0
```

Yields the tag a6124978:
```
docker.io/grafana/grafana@sha256:b7fcb534f7b3512801bb3f4e658238846435804deb479d105b5cdc680847c272=10.0.2.15:5000/grafana/grafana:a6124978
NAME                            TAG
10.0.2.15:5000/grafana/grafana  a6124978
```
Instead of the expected 10.4.3.

Creating a Grafana instance in the Grafana Operator in Openshift tries to pull the grafana container by tag 10.4.3, so it can't find it.
